require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TalliesController do

  # This should return the minimal set of attributes required to create a valid
  # Tally. As you add validations to Tally, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TalliesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tallies as @tallies" do
      tally = Tally.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tallies).should eq([tally])
    end
  end

  describe "GET show" do
    it "assigns the requested tally as @tally" do
      tally = Tally.create! valid_attributes
      get :show, {:id => tally.to_param}, valid_session
      assigns(:tally).should eq(tally)
    end
  end

  describe "GET new" do
    it "assigns a new tally as @tally" do
      get :new, {}, valid_session
      assigns(:tally).should be_a_new(Tally)
    end
  end

  describe "GET edit" do
    it "assigns the requested tally as @tally" do
      tally = Tally.create! valid_attributes
      get :edit, {:id => tally.to_param}, valid_session
      assigns(:tally).should eq(tally)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tally" do
        expect {
          post :create, {:tally => valid_attributes}, valid_session
        }.to change(Tally, :count).by(1)
      end

      it "assigns a newly created tally as @tally" do
        post :create, {:tally => valid_attributes}, valid_session
        assigns(:tally).should be_a(Tally)
        assigns(:tally).should be_persisted
      end

      it "redirects to the created tally" do
        post :create, {:tally => valid_attributes}, valid_session
        response.should redirect_to(Tally.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tally as @tally" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tally.any_instance.stub(:save).and_return(false)
        post :create, {:tally => {}}, valid_session
        assigns(:tally).should be_a_new(Tally)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tally.any_instance.stub(:save).and_return(false)
        post :create, {:tally => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tally" do
        tally = Tally.create! valid_attributes
        # Assuming there are no other tallies in the database, this
        # specifies that the Tally created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tally.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tally.to_param, :tally => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tally as @tally" do
        tally = Tally.create! valid_attributes
        put :update, {:id => tally.to_param, :tally => valid_attributes}, valid_session
        assigns(:tally).should eq(tally)
      end

      it "redirects to the tally" do
        tally = Tally.create! valid_attributes
        put :update, {:id => tally.to_param, :tally => valid_attributes}, valid_session
        response.should redirect_to(tally)
      end
    end

    describe "with invalid params" do
      it "assigns the tally as @tally" do
        tally = Tally.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tally.any_instance.stub(:save).and_return(false)
        put :update, {:id => tally.to_param, :tally => {}}, valid_session
        assigns(:tally).should eq(tally)
      end

      it "re-renders the 'edit' template" do
        tally = Tally.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tally.any_instance.stub(:save).and_return(false)
        put :update, {:id => tally.to_param, :tally => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tally" do
      tally = Tally.create! valid_attributes
      expect {
        delete :destroy, {:id => tally.to_param}, valid_session
      }.to change(Tally, :count).by(-1)
    end

    it "redirects to the tallies list" do
      tally = Tally.create! valid_attributes
      delete :destroy, {:id => tally.to_param}, valid_session
      response.should redirect_to(tallies_url)
    end
  end

end
